version: '3'
services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: sh -c "dockerize -wait tcp://db:3306 -timeout 40s -wait-retry-interval 2s && node index.js"
    tty: true
    volumes:
      - ./node:/app
    ports: 
      - 8080:8080
    networks:
      - node-network
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=node
    networks:
      - node-network
    ports:
      - 3306:3306
networks:
  node-network:
    driver: bridge