version: '3'
services:
  laravel:
    image: 'xokys/laravel:latest'
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: 'xokys/nginx:latest'
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
