version: '3'
services:
  laravel:
    build:
      context: './laravel'
    image: 'xokys/laravel:v1'
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: './nginx'
    image: 'xokys/nginx:v1'
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
